name: Publish Packages

on:
  push:
    branches:
      - master

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  publish:
    needs: checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn
        registry-url: https://registry.npmjs.org

    - name: Configure Git user
      run: |
        git config user.email "<>"
        git config user.name "Github Actions Bot"

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Publish packages
      run: lerna publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
