name: Publish Packages

on:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Hack to bypass detached HEAD in PR
      run: git checkout naj-12-publish-ci

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn
        registry-url: https://registry.npmjs.org

    - name: Configure Git user
      run: |
        git config user.email "<>"
        git config user.name "Github Actions Bot"

    - run: git log --oneline

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Build dependencies
      run: yarn build

    - name: Publish packages
      run: lerna publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
